### ISSUE TITLE
Wrong d3/jquery versions used in html - console broken

### ISSUE THREAD

**Issue by cshapeshifter** [uzh/signal-collect#157]
With 3.0.2, some [web-jars were updated](https://github.com/uzh/signal-collect/commit/45820741adb5f56f0885f6d3d3743e9c61e7d036), but the [corresponding html](https://github.com/uzh/signal-collect/blob/master/src/main/resources/web-data/html/main.html#L28) wasn't. The web-jar versions are d3 3.5.5 and jquery 2.1.4, but the following versions are used, causing 404s:

```
    <script type="text/javascript" src="webjars/jquery/2.1.3/jquery.js"></script>
    <script type="text/javascript" src="webjars/d3js/3.5.2/d3.js"></script>
```

PS: Thanks for fixing #154!

**Comment by pstutz** [comment]
Thanks for reporting this bug and sorry for the oversight. It's fixed in the new release 3.0.3.
